### ISSUE TITLE
installation inconvenience

### ISSUE THREAD

**Issue by nikhil-swamix** [namecheap/fast_mail_parser#11]
while i greatly appreciate the package and have successfully run tests as per readme.
but the installation was quite slow 

1. i saw cargo was downloading at 10mbps, which made total installation time to 1 min.

im not sure what the internals are, but does it build something? and does it require rust to be installed?

query: is there a pre compiled binary available from faster server which i may use in bundle, or my understanding is wrong ?

**Comment by SaulTigh** [comment]
hey, we are working on releasing wheels to support more platforms, expect release soon

**Comment by nikhil-swamix** [comment]
nice, just keep things pip install, and done. 
regards
