### ISSUE TITLE
Non utf-8 encoded mail is not handled correctly

### ISSUE THREAD

**Issue by huruka** [namecheap/fast_mail_parser#8]
When processing CJK emails, if the file encoding is not utf-8, CJK characters are not correctly recognized. 
But it can be correctly identified with [eml_parser](https://github.com/GOVCERT-LU/eml_parser).
Test email available if needed.

**Comment by sokyrko** [comment]
Hi.
Please share the test email that I can use to reproduce the problem and eventually use it as a sample for the library tests.

**Comment by sokyrko** [comment]
@huruka 
It happens because Python doesn't support non-utf8 chars in strings. Try reading the file as bytes:
```python
with open(filepath, 'rb') as f:
    message_payload = f.read()
```

**Comment by sokyrko** [comment]
@alterago please close the issue

**Comment by huruka** [comment]
Thank you! Using rb mode does display the content correctly.
